DROP DATABASE IF EXISTS aca_gestor_tickets;

CREATE DATABASE IF NOT EXISTS aca_gestor_tickets CHARACTER SET "utf8" COLLATE "utf8_spanish2_ci";

USE aca_gestor_tickets;

DROP TABLE IF EXISTS aca_tipo_usuario;

CREATE TABLE IF NOT EXISTS aca_tipo_usuario (
  id_tipo_usuario INT NOT NULL AUTO_INCREMENT,
  nombre_tipo_usuario VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id_tipo_usuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

INSERT INTO aca_tipo_usuario (nombre_tipo_usuario, created_at, updated_at)
VALUES
('ADMINISTRADOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SUPERVISOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COLABORADOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS aca_agencias;

CREATE TABLE IF NOT EXISTS aca_agencias (
  id_agencia INT NOT NULL AUTO_INCREMENT,
  nombre_agencia VARCHAR(150) NOT NULL,
  direccion_agencia TEXT NULL,
  telefono_agencia TEXT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id_agencia)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

INSERT INTO aca_agencias (nombre_agencia, direccion_agencia, telefono_agencia, created_at, updated_at)
VALUES
('AGENCIA OLIMPICA', '71 Avenida Sur 3719, San Salvador', '2561-2300', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AGENCIA MERLIOT', 'Centro Comercial Plaza Merliot Tercer Nivel Local #396', '2288-2103', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AGENCIA ROOSEVELT', 'Alameda Roosevelt y 37 Av.Norte,N° 2002, 2300, PBX.2239, San Salvador', '2561-2300', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS aca_departamentos;

CREATE TABLE IF NOT EXISTS `aca_departamentos` (
  `id_departamento` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_departamento` varchar(100) COLLATE utf8_spanish2_ci DEFAULT NULL,
  `descripcion_departamento` text COLLATE utf8_spanish2_ci,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (`id_departamento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

INSERT INTO `aca_departamentos` (`nombre_departamento`, `descripcion_departamento`, created_at, updated_at) VALUES
('ADMINISTRACION', 'ADMINISTRACION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RECURSOS HUMANOS', 'RECURSOS HUMANOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('FINANZAS', 'FINANZAS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MERCADEO Y CAJAS', 'MERCADEO Y CAJAS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CREDITOS', 'CREDITOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COBROS', 'COBROS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JURIDICO', 'JURIDICO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ADMINISTRACION FINANCIERA', 'ADMINISTRACION FINANCIERA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OFICIALIA CUMPLIMIENTO', 'OFICIALIA CUMPLIMIENTO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GERENCIA GENERAL', 'GERENCIA GENERAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COMITES DE RIESGO', 'COMITES DE RIESGO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CONSEJO DE ADMINISTRACION', 'CONSEJO DE ADMINISTRACION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AGENCIA ROOSEVELT', 'AGENCIA ROOSEVELT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AGENCIA MERLIOT', 'AGENCIA MERLIOT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('INFORMATICA', 'INFORMATICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COMITE DE MORA', 'COMITE DE MORA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COMITE DE EDUCACION', 'COMITE DE EDUCACION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COMITE DE CREDITOS', 'COMITE DE CREDITOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JUNTA DE VIGILANCIA', 'JUNTA DE VIGILANCIA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NEGOCIOS', 'NEGOCIOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COMITE DE AUDITORIA', 'COMITE AUDITORIA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ATENCION AL ASOCIADO Y CAJAS', 'ATENCION AL ASOCIADO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OPERACIONES', 'OPERACIONES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('FIDELIZACION', 'FIDELIZACION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CONTABILIDAD', 'CONTABILIDAD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS aca_puestos;

CREATE TABLE IF NOT EXISTS aca_puestos (
  id_puesto INT NOT NULL AUTO_INCREMENT,
  nombre_puesto VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id_puesto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

INSERT INTO `aca_puestos` (`nombre_puesto`, created_at, updated_at)
VALUES
('GERENTE GENERAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE ADMINISTRATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COORDINADOR DE RECURSOS HUMANOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ASISTENTE ADMINISTRATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR ADMINISTRATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GESTOR ADMINISTRATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR DE SERVICIOS CENTRO DE RECREO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR SERVICIOS GENERALES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SEGURIDAD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE JURIDICO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COLABORADOR JURIDICO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ASISTENTE JURIDICO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR JURIDICO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE DE FINANZAS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COORDINADOR DE INFORMATICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR DE INFORMATICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR PROCESAMIENTO DE DATOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ASISTENTE CONTABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR CONTABLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE DE NEGOCIOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COORDINADOR DE MERCADEO Y COMUNICACIONES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COORDINADOR DE COBROS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE DE AGENCIA OLIMPICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OFICIAL DE NEGOCIOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR DE CREDITOS Y COBROS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR DE MERCADEO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CAJERO/A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RECEPCION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE DE AGENCIA ROOSEVELT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR ADMINISTRATIVO DE AGENCIA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AUXILIAR DE SERVICIOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE DE AGENCIA MERLIOT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('OFICIAL DE CUMPLIMIENTO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COMITES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CONSEJO DE ADMINISTRACION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ASISTENTE DE GERENCIA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MERCADEO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COORDINADOR DE COBROS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE DE MERCADEO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('JEFE DE OPERACIONES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COORDINADORA DE FIDELIZACION Y RETENCION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ASISTENTE DE TESORERIA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id_usuario INT NOT NULL AUTO_INCREMENT,
  codigo_usuario VARCHAR(45) NOT NULL,
  nombre_usuario TEXT NOT NULL,
  apellido_usuario TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  numero_usuario TEXT NULL,
  id_tipo_usuario INT NOT NULL,
  id_agencia INT NOT NULL,
  id_departamento INT NOT NULL,
  id_puesto INT NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id_usuario),
  FOREIGN KEY (id_tipo_usuario) REFERENCES aca_tipo_usuario (id_tipo_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_agencia) REFERENCES aca_agencias (id_agencia) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_departamento) REFERENCES aca_departamentos (id_departamento) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_puesto) REFERENCES aca_puestos (id_puesto) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

INSERT INTO users (codigo_usuario, nombre_usuario, apellido_usuario, email, password, id_tipo_usuario, id_agencia, id_departamento, id_puesto, created_at, updated_at)
VALUES
('admin', 'Súper', 'Administrador', 'admin@gmail', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS aca_tipo_problema;

CREATE TABLE IF NOT EXISTS aca_tipo_problema (
  id_tipo_problema INT NOT NULL AUTO_INCREMENT,
  nombre_tipo_problema TEXT NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id_tipo_problema)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

INSERT INTO aca_tipo_problema (nombre_tipo_problema, created_at, updated_at)
VALUES
('PROBLEMA SISTEMA OPERATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PROBLEMA IMPRESORA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PROBLEMA DE INTERNET', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS aca_tipo_solucion;

CREATE TABLE IF NOT EXISTS aca_tipo_solucion (
  id_tipo_solucion INT NOT NULL AUTO_INCREMENT,
  nombre_tipo_solucion TEXT NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id_tipo_solucion)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

INSERT INTO aca_tipo_solucion (nombre_tipo_solucion, created_at, updated_at)
VALUES
('REINSTALACIÓN DE SO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CORRECCIÓN DE IP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CAMBIO DE CABLE INTERNET', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS aca_estados_ticket;

CREATE TABLE IF NOT EXISTS aca_estados_ticket (
  id_estado_ticket INT NOT NULL AUTO_INCREMENT,
  nombre_estado_ticket TEXT NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id_estado_ticket)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

INSERT INTO aca_estados_ticket (nombre_estado_ticket, created_at, updated_at)
VALUES
('EN ESPERA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('EN COLA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('EN PROCESO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RESUELTO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('REPROGRAMADO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('VENCIDO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CERRADO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS aca_tickets;

CREATE TABLE IF NOT EXISTS aca_tickets(
  id_ticket INT NOT NULL AUTO_INCREMENT,
  id_usuario INT NOT NULL,
  id_tipo_problema INT NOT NULL,
  descripcion_problema_ticket TEXT NOT NULL,
  id_estado_ticket INT NOT NULL,
  fecha_inicio_ticket TIMESTAMP NULL,
  fecha_fin_ticket TIMESTAMP NULL,
  tiempo_solucion_ticket TEXT NULL,
  id_solucionador INT NOT NULL,
  id_tipo_solucion INT NOT NULL,
  descripcion_solucion_ticket TEXT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id_ticket),
  FOREIGN KEY (id_usuario) REFERENCES users (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_tipo_problema) REFERENCES aca_tipo_problema (id_tipo_problema) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_estado_ticket) REFERENCES aca_estados_ticket (id_estado_ticket) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_solucionador) REFERENCES users (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_tipo_solucion) REFERENCES aca_tipo_solucion (id_tipo_solucion) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

DROP DATABASE IF EXISTS aca_asignacion_problema;

CREATE TABLE IF NOT EXISTS aca_asignacion_problema(
  id_asignacion_problema INT NOT NULL AUTO_INCREMENT,
  id_ticket INT NOT NULL,
  id_puesto INT NOT NULL,
  id_tipo_problema INT NOT NULL,
  PRIMARY KEY (id_asignacion_problema),
  FOREIGN KEY (id_ticket) REFERENCES aca_tickets (id_ticket) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_puesto) REFERENCES aca_puestos (id_puesto) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_tipo_problema) REFERENCES aca_tipo_problema (id_tipo_problema) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;